[ar]
data = "بيانات"
name = "الإسم"
services = "خدمات"
website = "موقع"
websites = "مواقع"
tags = "وسوم"
skills = "مهارات"
description = "وصف"
contact_accounts = "حسابات_تواصل"
contact_accounts_title = "وسائل تواصل"
services_of = "خدمات"
file_format = "تنسيق_الملف"
category = "صنف"
sub_category = "صنف_فرعي"
service_image = "صورة الخدمة"
price = "أجرة الخدمة"
hourly_rate = "أجرة_الساعة"
title = "عنوان"
user_description = "وصف_المستخدم"
profile_image = "صورة_الملف"

[en]
data = "data"
name = "name"
services = "services"
website = "website"
tags = "tags"
skills = "skills"
description = "description"
contact_accounts = "contact_accounts"
websites = "websites"
contact_accounts_title = "Contact Accounts"
services_of = "Services of"
file_format = "file_format"
category = "category"
sub_category = "sub_category"
service_image = "service_image"
title = "title"
price = "price"
hourly_rate = "hourly_rate"
user_description = "user_description"
profile_image = "profile_image"
